/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d75d6b4f-a940-4dc1-9e26-b9398ce2c7ee",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WE18pqPdD",
    "aws_user_pools_web_client_id": "61nk33klfoe0dd1fvjhojbg9pl",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://f6hnux2afnb7vorhjykrbepfly.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b7surpybafgwxn5yfjkbgeup4q",
    "aws_user_files_s3_bucket": "amplifyapp8307c6eaa77941a3b516fd8ddc477350180728-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
